# Generated by Django 5.2 on 2025-04-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0004_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
